"""adding the ability to remove both the paste and the linked columns in the pastetag table

Revision ID: 6714457b92f7
Revises: fc9e778243f5
Create Date: 2026-09-17 20:06:54.229599

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "6714457b92f7"
down_revision: str | Sequence[str] | None = "fc9e778243f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
