"""fixed the primer issue of removing paste when having many to many relationship to make it at the database level

Revision ID: 727813286c2b
Revises: 6714457b92f7
Create Date: 2026-09-17 21:24:56.950277

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "727813286c2b"
down_revision: Union[str, Sequence[str], None] = "6714457b92f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("PasteTag_tag_id_fkey"), "PasteTag", type_="foreignkey")
    op.drop_constraint(op.f("PasteTag_paste_id_fkey"), "PasteTag", type_="foreignkey")
    op.create_foreign_key(
        None, "PasteTag", "tags", ["tag_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "PasteTag", "pastes", ["paste_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "PasteTag", type_="foreignkey")
    op.drop_constraint(None, "PasteTag", type_="foreignkey")
    op.create_foreign_key(
        op.f("PasteTag_paste_id_fkey"), "PasteTag", "pastes", ["paste_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("PasteTag_tag_id_fkey"), "PasteTag", "tags", ["tag_id"], ["id"]
    )
    # ### end Alembic commands ###
