"""added the role field in the table user for RBAC

Revision ID: dd2507916344
Revises: b70cf09ea3f8
Create Date: 2026-09-22 13:21:20.272894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dd2507916344'
down_revision: Union[str, Sequence[str], None] = 'b70cf09ea3f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pastes', 'is_private',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('users', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.alter_column('pastes', 'is_private',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
