"""adding index to the content column in the Paste with the data structure of gin_trm

Revision ID: fc9e778243f5
Revises: cad852481fe1
Create Date: 2026-09-16 13:31:08.185458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc9e778243f5'
down_revision: Union[str, Sequence[str], None] = 'cad852481fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS pg_trgm"))
    op.create_index('content_idx', 'pastes', ['content'], unique=False, postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('content_idx', table_name='pastes')
    # ### end Alembic commands ###
